language: rust
rust:
  - nightly-2019-11-06

os:
  - linux

cache: rust

install:
  - rustup target add thumbv7em-none-eabi
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo test --lib --all
  - ./build_examples.sh
